INSERT INTO USERS VALUES('msk1416', 'Sergi', 'Mascaro');
INSERT INTO USERS VALUES('bstinson', 'Barney', 'Stinson');
INSERT INTO USERS VALUES('user2204', 'Commonname', 'Commonlastname');

CREATE SEQUENCE id_seq
  START WITH 1
  INCREMENT BY 1;
  
  
CREATE INDEX XMLINDEX ON SONGS(INFO) 
       INDEXTYPE IS CTXSYS.CONTEXT;