/* run as sysdba */
CREATE OR REPLACE DIRECTORY XML_DIR AS '/home/oracle/guest_share/git/XML_MDB/xml';
GRANT READ,WRITE ON DIRECTORY XML_DIR TO MDB;
COMMIT;

CREATE OR REPLACE DIRECTORY EXPORTS_DIR AS '/home/oracle/guest_share/git/XML_MDB/exports';
GRANT READ,WRITE ON DIRECTORY EXPORTS_DIR TO MDB;
COMMIT;

SET SERVEROUTPUT ON;

