/* users table creation script */
CREATE TABLE USERS (
  USERNAME VARCHAR2(50 CHAR) NOT NULL, 
  FIRST_NAME VARCHAR2(50 CHAR), 
  LAST_NAME VARCHAR2(50 CHAR), 
  CONSTRAINT USERS_PK PRIMARY KEY (USERNAME) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);

/* songs table creation script */
CREATE TABLE SONGS (
  ID NUMBER NOT NULL, 
  URI VARCHAR2(200 BYTE) NOT NULL, 
  INFO SYS.XMLTYPE, 
  CONSTRAINT TABLE1_PK PRIMARY KEY (ID) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
) XMLTYPE INFO STORE AS CLOB;
ALTER TABLE 
  SONGS 
ADD 
  CONSTRAINT TABLE1_UK1 UNIQUE (URI) ENABLE;
CREATE INDEX XMLINDEX ON SONGS (
  SYS_MAKEXML("SYS_NC00004$") ASC
) LOGGING PCTFREE 0 STORAGE (BUFFER_POOL DEFAULT);

/* playlist table creation script */
CREATE TABLE PLAYLISTS (
  OWNER VARCHAR2(20 BYTE) NOT NULL, 
  SONG NUMBER NOT NULL, 
  NAME VARCHAR2(20 BYTE) NOT NULL, 
  CONSTRAINT PLAYLISTS_PK PRIMARY KEY (OWNER, NAME, SONG) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
ALTER TABLE 
  PLAYLISTS 
ADD 
  CONSTRAINT PLAYLISTS_SONGS_FK1 FOREIGN KEY (SONG) REFERENCES SONGS (ID) ENABLE;
ALTER TABLE 
  PLAYLISTS 
ADD 
  CONSTRAINT PLAYLISTS_USERS_FK1 FOREIGN KEY (OWNER) REFERENCES USERS (USERNAME) ENABLE;
